---
title: "GSE48278"
date: "7/11/2021"
output: html_document
---


## GSE48278
**Various exercise groups, both sex**  

- **journal:** https://link.springer.com/article/10.1007/s00125-014-3343-4
- **GEO:** https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE48278


- A: Mild aerobic exercise - low amount/mod intensity n=10
- B: Inactive control n=10
- C: High aerobic exercise - high amt/vig intensity n=10
- D: Moderate aerobic exercise - low amt/vig intensity n=10
- E: Mod aerobic + resistance training n=8
- F: Resistance training only n=9

In our analysis, we compared pre & post of exercise training within a group. Group B was excluded.  


- GPL570	[HG-U133_Plus_2] Affymetrix Human Genome U133 Plus 2.0 Array
- E-GEOD-48278


## Results  
**after adding exprs(final) <- log2(exprs(final))**  
7/12/2021  
res_GSE48278reFA.csv 
p < 0.05: 656 
p < 0.01: 82 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278reFC.csv 
p < 0.05: 3246 
p < 0.01: 417 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278reFD.csv 
p < 0.05: 3006 
p < 0.01: 413 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278reFE.csv 
p < 0.05: 2824 
p < 0.01: 466 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278reFF.csv 
p < 0.05: 176 
p < 0.01: 10 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278reMA.csv 
p < 0.05: 643 
p < 0.01: 67 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278reMC.csv 
p < 0.05: 518 
p < 0.01: 57 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278reMD.csv 
p < 0.05: 1470 
p < 0.01: 188 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278reME.csv 
p < 0.05: 3184 
p < 0.01: 556 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278reMF.csv 
p < 0.05: 1962 
p < 0.01: 207 
adj.P < 0.05: 0 
adj.P < 0.01: 0

<br>

cf. Using `gse`  
res_GSE48278gseFA.csv 
p < 0.05: 650 
p < 0.01: 77 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278gseFC.csv 
p < 0.05: 3247 
p < 0.01: 416 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278gseFD.csv 
p < 0.05: 3012 
p < 0.01: 417 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278gseFE.csv 
p < 0.05: 2826 
p < 0.01: 468 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278gseFF.csv 
p < 0.05: 171 
p < 0.01: 10 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278gseMA.csv 
p < 0.05: 644 
p < 0.01: 69 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278gseMC.csv 
p < 0.05: 519 
p < 0.01: 55 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278gseMD.csv 
p < 0.05: 1472 
p < 0.01: 190 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278gseME.csv 
p < 0.05: 3191 
p < 0.01: 564 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278gseMF.csv 
p < 0.05: 1958 
p < 0.01: 210 
adj.P < 0.05: 0 
adj.P < 0.01: 0 


**memo: Similar results with the one using `norm` data**  
<br>


**non log-transformed data**
res_GSE48278FA.csv 
p < 0.05: 1093 
p < 0.01: 120 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278FC.csv 
p < 0.05: 4295 
p < 0.01: 1062 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278FD.csv 
p < 0.05: 3373 
p < 0.01: 686 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278FE.csv 
p < 0.05: 3144 
p < 0.01: 737 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278FF.csv 
p < 0.05: 848 
p < 0.01: 62 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278MA.csv 
p < 0.05: 663 
p < 0.01: 65 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278MC.csv 
p < 0.05: 815 
p < 0.01: 77 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278MD.csv 
p < 0.05: 1927 
p < 0.01: 420 
adj.P < 0.05: 0 
adj.P < 0.01: 0 

res_GSE48278ME.csv 
p < 0.05: 3895 
p < 0.01: 1212 
adj.P < 0.05: 2 
adj.P < 0.01: 0 

res_GSE48278MF.csv 
p < 0.05: 2817 
p < 0.01: 667 
adj.P < 0.05: 0 
adj.P < 0.01: 0 



